#relevant folders 
paths:

  output_folder: "data/output"
  # output_folder = "/home/cir/tdeimel/autoscoRA/autoscoRA_Preprocessing/output/test"
  dicom_server: "data"
  # dicom_server = "/home/cir/tdeimel/autoscoRA/autoscoRA_Preprocessing/sample_xrays"
  data_folder: "data/raw"
  # data_folder = "/home/cir/tdeimel/autoscoRA/autoscoRA_Preprocessing/data"
  logger : "src/logger"

tags: {'pat_id': '0010|0010',
           'study_date': '0008|0020',
           'accession_nr': '0008|0050',
           'modality': '0008|0060',
           'body_part_examined': '0018|0015',
           'laterality': '0020|0060',
           'view_position': '0018|5101',
           'series_description': '0008|103e',
           'series_description_code': '0008|103f',
           'study_description': '0008|1030',
           'pixel_spacing': '0028|0030',
           'imager_pixel_spacing': '0018|1164',
           'samples_per_pixel': '0028|0002',
           'rows': '0028|0010',
           'columns': '0028|0011',
           'photometric_interpretation': '0028|0004'}




